# Generated by Django 2.0.4 on 2018-04-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=20)),
                ('verifivation', models.BooleanField(default=False)),
            ],
        ),
    ]
